apiVersion: v1
data:
  oauth2-proxy-alpha-config.yaml: "server:\n  BindAddress: \"0.0.0.0:4180\"\nupstreamConfig:\n
    \ proxyRawPath: true\n  upstreams:\n    - id: static\n      path: //\n      static:
    true\n      staticCode: 202\nproviders:\n  - provider: keycloak-oidc\n    id:
    keycloak-oidc\n    clientSecret: b79feb6f-7b5a-45ee-9763-75dee82cb27f\n    clientID:
    hypercloud5\n    oidcConfig:\n      issuerURL: https://hyperauth.tmaxcloud.org/auth/realms/tmax
    \         \n      emailClaim: preferred_username\n      audienceClaims:\n        -
    aud\n      userIDClaim: preferred_username\ninjectResponseHeaders:\n  - name:
    Authorization\n    values:\n      - claim: access_token\n        prefix: \"Bearer
    \"\n  - name: X-Auth-Request-Access-Token\n    values:\n      - claim: access_token"
  oauth2-proxy.cfg: |-
    cookie_secret="OQINaROshtE9TcZkNAm-5Zs2Pv3xaWytBmc5W7sPX7w="
    email_domains="*"
    cookie_secure="true"
    redirect_url="https://auth.tmaxcloud.org/oauth2/callback"
    reverse_proxy="true"
kind: ConfigMap
metadata:
  annotations:
    createdTime: "2022-03-29T14:31:16.43523371+09:00"
    creator: kubernetes-admin
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"oauth2-proxy-alpha-config.yaml":"server:\n  BindAddress: \"0.0.0.0:4180\"\nupstreamConfig:\n  proxyRawPath: true\n  upstreams:\n    - id: static\n      path: //\n      static: true\n      staticCode: 202\nproviders:\n  - provider: keycloak-oidc\n    id: keycloak-oidc\n    clientSecret: b79feb6f-7b5a-45ee-9763-75dee82cb27f\n    clientID: hypercloud5\n    oidcConfig:\n      issuerURL: https://hyperauth.tmaxcloud.org/auth/realms/tmax          \n      emailClaim: preferred_username\n      audienceClaims:\n        - aud\n      userIDClaim: preferred_username\ninjectResponseHeaders:\n  - name: Authorization\n    values:\n      - claim: access_token\n        prefix: \"Bearer \"\n  - name: X-Auth-Request-Access-Token\n    values:\n      - claim: access_token","oauth2-proxy.cfg":"cookie_secret=\"OQINaROshtE9TcZkNAm-5Zs2Pv3xaWytBmc5W7sPX7w=\"\nemail_domains=\"*\"\ncookie_secure=\"true\"\nredirect_url=\"https://auth.tmaxcloud.org/oauth2/callback\"\nreverse_proxy=\"true\""},"kind":"ConfigMap","metadata":{"annotations":{},"name":"oauth2-proxy","namespace":"api-gateway-system"}}
    updatedTime: "2022-03-29T14:31:16.43523371+09:00"
    updater: kubernetes-admin
  creationTimestamp: "2022-03-29T05:31:16Z"
  name: oauth2-proxy
  namespace: api-gateway-system
  resourceVersion: "370845810"
  selfLink: /api/v1/namespaces/api-gateway-system/configmaps/oauth2-proxy
  uid: 57567263-67fe-41f7-9308-aed7e9e00a3f
